// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class BandwidthSummaryStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoBandwidthSummaryStats reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoBandwidthSummaryStatsGetactualEncoderBitRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoBandwidthSummaryStatsGetavailableBandwidthNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoBandwidthSummaryStatsGetleakyBucketDelayNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoBandwidthSummaryStatsGetretransmitBitRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoBandwidthSummaryStatsGettargetEncoderBitRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoBandwidthSummaryStatsGettotalTransmitBitRateNative(IntPtr obj);

		public ulong actualEncoderBitRate;
		public ulong availableBandwidth;
		public ulong leakyBucketDelay;
		public ulong retransmitBitRate;
		public ulong targetEncoderBitRate;
		public ulong totalTransmitBitRate;
		public BandwidthSummaryStats(IntPtr obj){
			objPtr = obj;

			actualEncoderBitRate = VidyoBandwidthSummaryStatsGetactualEncoderBitRateNative(objPtr);
			availableBandwidth = VidyoBandwidthSummaryStatsGetavailableBandwidthNative(objPtr);
			leakyBucketDelay = VidyoBandwidthSummaryStatsGetleakyBucketDelayNative(objPtr);
			retransmitBitRate = VidyoBandwidthSummaryStatsGetretransmitBitRateNative(objPtr);
			targetEncoderBitRate = VidyoBandwidthSummaryStatsGettargetEncoderBitRateNative(objPtr);
			totalTransmitBitRate = VidyoBandwidthSummaryStatsGettotalTransmitBitRateNative(objPtr);
		}
	};
}
