// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class CalendarManagerFeedback{
		private IntPtr objPtr; //opaque VidyoCalendarManagerFeedback reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
	};
}
