// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class EndpointStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoEndpointStats reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetapplicationTagNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetbuildTagNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetbytesReceivedTcpNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetbytesReceivedUdpNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetbytesSentTcpNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetbytesSentUdpNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetconnectTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlibraryVersionNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalCameraStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalCameraStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreelocalCameraStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalMicrophoneStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalMicrophoneStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreelocalMicrophoneStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalMonitorStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalMonitorStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreelocalMonitorStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalRendererStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalRendererStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreelocalRendererStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalSpeakerStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalSpeakerStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreelocalSpeakerStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalWindowShareStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlocalWindowShareStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreelocalWindowShareStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetlogStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetloginTimeConsumedMsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetmaxBitRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetmaxEncodePixelRateInitialNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetmediaEnableTimeConsumedMsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetmediaRouteAcquireTimeConsumedMsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetnetworkInterfaceStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetnetworkInterfaceStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreenetworkInterfaceStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetosNameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetosVersionNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetprocessorBrandNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoEndpointStatsGetprocessorLogicalCoresNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetprocessorModelNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoEndpointStatsGetprocessorPhysicalCoresNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoEndpointStatsGetprocessorSpeedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoEndpointStatsGetroomEnterTimeConsumedMsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGettimeStampNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetuserStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetuserStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreeuserStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetvirtualWindowShareStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointStatsGetvirtualWindowShareStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointStatsFreevirtualWindowShareStatsArrayNative(IntPtr obj, int size);

		public String applicationTag;
		public String buildTag;
		public ulong bytesReceivedTcp;
		public ulong bytesReceivedUdp;
		public ulong bytesSentTcp;
		public ulong bytesSentUdp;
		public String connectTime;
		public String id;
		public String libraryVersion;
		public List<LocalVideoSourceStats> localCameraStats;
		public List<LocalMicrophoneStats> localMicrophoneStats;
		public List<LocalVideoSourceStats> localMonitorStats;
		public List<LocalRendererStats> localRendererStats;
		public List<LocalSpeakerStats> localSpeakerStats;
		public List<LocalVideoSourceStats> localWindowShareStats;
		public LogStats logStats;
		public ulong loginTimeConsumedMs;
		public ulong maxBitRate;
		public ulong maxEncodePixelRateInitial;
		public ulong mediaEnableTimeConsumedMs;
		public ulong mediaRouteAcquireTimeConsumedMs;
		public List<NetworkInterfaceStats> networkInterfaceStats;
		public String osName;
		public String osVersion;
		public String processorBrand;
		public uint processorLogicalCores;
		public String processorModel;
		public uint processorPhysicalCores;
		public uint processorSpeed;
		public ulong roomEnterTimeConsumedMs;
		public String timeStamp;
		public List<UserStats> userStats;
		public List<LocalVideoSourceStats> virtualWindowShareStats;
		public EndpointStats(IntPtr obj){
			objPtr = obj;

			List<LocalVideoSourceStats> csLocalCameraStats = new List<LocalVideoSourceStats>();
			int nLocalCameraStatsSize = 0;
			IntPtr nLocalCameraStats = VidyoEndpointStatsGetlocalCameraStatsArrayNative(VidyoEndpointStatsGetlocalCameraStatsNative(objPtr), ref nLocalCameraStatsSize);
			int nLocalCameraStatsIndex = 0;
			while (nLocalCameraStatsIndex < nLocalCameraStatsSize) {
				LocalVideoSourceStats csTlocalCameraStats = new LocalVideoSourceStats(Marshal.ReadIntPtr(nLocalCameraStats + (nLocalCameraStatsIndex * Marshal.SizeOf(nLocalCameraStats))));
				csLocalCameraStats.Add(csTlocalCameraStats);
				nLocalCameraStatsIndex++;
			}

			List<LocalMicrophoneStats> csLocalMicrophoneStats = new List<LocalMicrophoneStats>();
			int nLocalMicrophoneStatsSize = 0;
			IntPtr nLocalMicrophoneStats = VidyoEndpointStatsGetlocalMicrophoneStatsArrayNative(VidyoEndpointStatsGetlocalMicrophoneStatsNative(objPtr), ref nLocalMicrophoneStatsSize);
			int nLocalMicrophoneStatsIndex = 0;
			while (nLocalMicrophoneStatsIndex < nLocalMicrophoneStatsSize) {
				LocalMicrophoneStats csTlocalMicrophoneStats = new LocalMicrophoneStats(Marshal.ReadIntPtr(nLocalMicrophoneStats + (nLocalMicrophoneStatsIndex * Marshal.SizeOf(nLocalMicrophoneStats))));
				csLocalMicrophoneStats.Add(csTlocalMicrophoneStats);
				nLocalMicrophoneStatsIndex++;
			}

			List<LocalVideoSourceStats> csLocalMonitorStats = new List<LocalVideoSourceStats>();
			int nLocalMonitorStatsSize = 0;
			IntPtr nLocalMonitorStats = VidyoEndpointStatsGetlocalMonitorStatsArrayNative(VidyoEndpointStatsGetlocalMonitorStatsNative(objPtr), ref nLocalMonitorStatsSize);
			int nLocalMonitorStatsIndex = 0;
			while (nLocalMonitorStatsIndex < nLocalMonitorStatsSize) {
				LocalVideoSourceStats csTlocalMonitorStats = new LocalVideoSourceStats(Marshal.ReadIntPtr(nLocalMonitorStats + (nLocalMonitorStatsIndex * Marshal.SizeOf(nLocalMonitorStats))));
				csLocalMonitorStats.Add(csTlocalMonitorStats);
				nLocalMonitorStatsIndex++;
			}

			List<LocalRendererStats> csLocalRendererStats = new List<LocalRendererStats>();
			int nLocalRendererStatsSize = 0;
			IntPtr nLocalRendererStats = VidyoEndpointStatsGetlocalRendererStatsArrayNative(VidyoEndpointStatsGetlocalRendererStatsNative(objPtr), ref nLocalRendererStatsSize);
			int nLocalRendererStatsIndex = 0;
			while (nLocalRendererStatsIndex < nLocalRendererStatsSize) {
				LocalRendererStats csTlocalRendererStats = new LocalRendererStats(Marshal.ReadIntPtr(nLocalRendererStats + (nLocalRendererStatsIndex * Marshal.SizeOf(nLocalRendererStats))));
				csLocalRendererStats.Add(csTlocalRendererStats);
				nLocalRendererStatsIndex++;
			}

			List<LocalSpeakerStats> csLocalSpeakerStats = new List<LocalSpeakerStats>();
			int nLocalSpeakerStatsSize = 0;
			IntPtr nLocalSpeakerStats = VidyoEndpointStatsGetlocalSpeakerStatsArrayNative(VidyoEndpointStatsGetlocalSpeakerStatsNative(objPtr), ref nLocalSpeakerStatsSize);
			int nLocalSpeakerStatsIndex = 0;
			while (nLocalSpeakerStatsIndex < nLocalSpeakerStatsSize) {
				LocalSpeakerStats csTlocalSpeakerStats = new LocalSpeakerStats(Marshal.ReadIntPtr(nLocalSpeakerStats + (nLocalSpeakerStatsIndex * Marshal.SizeOf(nLocalSpeakerStats))));
				csLocalSpeakerStats.Add(csTlocalSpeakerStats);
				nLocalSpeakerStatsIndex++;
			}

			List<LocalVideoSourceStats> csLocalWindowShareStats = new List<LocalVideoSourceStats>();
			int nLocalWindowShareStatsSize = 0;
			IntPtr nLocalWindowShareStats = VidyoEndpointStatsGetlocalWindowShareStatsArrayNative(VidyoEndpointStatsGetlocalWindowShareStatsNative(objPtr), ref nLocalWindowShareStatsSize);
			int nLocalWindowShareStatsIndex = 0;
			while (nLocalWindowShareStatsIndex < nLocalWindowShareStatsSize) {
				LocalVideoSourceStats csTlocalWindowShareStats = new LocalVideoSourceStats(Marshal.ReadIntPtr(nLocalWindowShareStats + (nLocalWindowShareStatsIndex * Marshal.SizeOf(nLocalWindowShareStats))));
				csLocalWindowShareStats.Add(csTlocalWindowShareStats);
				nLocalWindowShareStatsIndex++;
			}

			LogStats csLogStats = new LogStats(VidyoEndpointStatsGetlogStatsNative(objPtr));
			List<NetworkInterfaceStats> csNetworkInterfaceStats = new List<NetworkInterfaceStats>();
			int nNetworkInterfaceStatsSize = 0;
			IntPtr nNetworkInterfaceStats = VidyoEndpointStatsGetnetworkInterfaceStatsArrayNative(VidyoEndpointStatsGetnetworkInterfaceStatsNative(objPtr), ref nNetworkInterfaceStatsSize);
			int nNetworkInterfaceStatsIndex = 0;
			while (nNetworkInterfaceStatsIndex < nNetworkInterfaceStatsSize) {
				NetworkInterfaceStats csTnetworkInterfaceStats = new NetworkInterfaceStats(Marshal.ReadIntPtr(nNetworkInterfaceStats + (nNetworkInterfaceStatsIndex * Marshal.SizeOf(nNetworkInterfaceStats))));
				csNetworkInterfaceStats.Add(csTnetworkInterfaceStats);
				nNetworkInterfaceStatsIndex++;
			}

			List<UserStats> csUserStats = new List<UserStats>();
			int nUserStatsSize = 0;
			IntPtr nUserStats = VidyoEndpointStatsGetuserStatsArrayNative(VidyoEndpointStatsGetuserStatsNative(objPtr), ref nUserStatsSize);
			int nUserStatsIndex = 0;
			while (nUserStatsIndex < nUserStatsSize) {
				UserStats csTuserStats = new UserStats(Marshal.ReadIntPtr(nUserStats + (nUserStatsIndex * Marshal.SizeOf(nUserStats))));
				csUserStats.Add(csTuserStats);
				nUserStatsIndex++;
			}

			List<LocalVideoSourceStats> csVirtualWindowShareStats = new List<LocalVideoSourceStats>();
			int nVirtualWindowShareStatsSize = 0;
			IntPtr nVirtualWindowShareStats = VidyoEndpointStatsGetvirtualWindowShareStatsArrayNative(VidyoEndpointStatsGetvirtualWindowShareStatsNative(objPtr), ref nVirtualWindowShareStatsSize);
			int nVirtualWindowShareStatsIndex = 0;
			while (nVirtualWindowShareStatsIndex < nVirtualWindowShareStatsSize) {
				LocalVideoSourceStats csTvirtualWindowShareStats = new LocalVideoSourceStats(Marshal.ReadIntPtr(nVirtualWindowShareStats + (nVirtualWindowShareStatsIndex * Marshal.SizeOf(nVirtualWindowShareStats))));
				csVirtualWindowShareStats.Add(csTvirtualWindowShareStats);
				nVirtualWindowShareStatsIndex++;
			}

			applicationTag = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetapplicationTagNative(objPtr));
			buildTag = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetbuildTagNative(objPtr));
			bytesReceivedTcp = VidyoEndpointStatsGetbytesReceivedTcpNative(objPtr);
			bytesReceivedUdp = VidyoEndpointStatsGetbytesReceivedUdpNative(objPtr);
			bytesSentTcp = VidyoEndpointStatsGetbytesSentTcpNative(objPtr);
			bytesSentUdp = VidyoEndpointStatsGetbytesSentUdpNative(objPtr);
			connectTime = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetconnectTimeNative(objPtr));
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetidNative(objPtr));
			libraryVersion = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetlibraryVersionNative(objPtr));
			localCameraStats = csLocalCameraStats;
			localMicrophoneStats = csLocalMicrophoneStats;
			localMonitorStats = csLocalMonitorStats;
			localRendererStats = csLocalRendererStats;
			localSpeakerStats = csLocalSpeakerStats;
			localWindowShareStats = csLocalWindowShareStats;
			logStats = csLogStats;
			loginTimeConsumedMs = VidyoEndpointStatsGetloginTimeConsumedMsNative(objPtr);
			maxBitRate = VidyoEndpointStatsGetmaxBitRateNative(objPtr);
			maxEncodePixelRateInitial = VidyoEndpointStatsGetmaxEncodePixelRateInitialNative(objPtr);
			mediaEnableTimeConsumedMs = VidyoEndpointStatsGetmediaEnableTimeConsumedMsNative(objPtr);
			mediaRouteAcquireTimeConsumedMs = VidyoEndpointStatsGetmediaRouteAcquireTimeConsumedMsNative(objPtr);
			networkInterfaceStats = csNetworkInterfaceStats;
			osName = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetosNameNative(objPtr));
			osVersion = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetosVersionNative(objPtr));
			processorBrand = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetprocessorBrandNative(objPtr));
			processorLogicalCores = VidyoEndpointStatsGetprocessorLogicalCoresNative(objPtr);
			processorModel = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGetprocessorModelNative(objPtr));
			processorPhysicalCores = VidyoEndpointStatsGetprocessorPhysicalCoresNative(objPtr);
			processorSpeed = VidyoEndpointStatsGetprocessorSpeedNative(objPtr);
			roomEnterTimeConsumedMs = VidyoEndpointStatsGetroomEnterTimeConsumedMsNative(objPtr);
			timeStamp = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointStatsGettimeStampNative(objPtr));
			userStats = csUserStats;
			virtualWindowShareStats = csVirtualWindowShareStats;
			VidyoEndpointStatsFreevirtualWindowShareStatsArrayNative(nVirtualWindowShareStats, nVirtualWindowShareStatsSize);
			VidyoEndpointStatsFreeuserStatsArrayNative(nUserStats, nUserStatsSize);
			VidyoEndpointStatsFreenetworkInterfaceStatsArrayNative(nNetworkInterfaceStats, nNetworkInterfaceStatsSize);
			VidyoEndpointStatsFreelocalWindowShareStatsArrayNative(nLocalWindowShareStats, nLocalWindowShareStatsSize);
			VidyoEndpointStatsFreelocalSpeakerStatsArrayNative(nLocalSpeakerStats, nLocalSpeakerStatsSize);
			VidyoEndpointStatsFreelocalRendererStatsArrayNative(nLocalRendererStats, nLocalRendererStatsSize);
			VidyoEndpointStatsFreelocalMonitorStatsArrayNative(nLocalMonitorStats, nLocalMonitorStatsSize);
			VidyoEndpointStatsFreelocalMicrophoneStatsArrayNative(nLocalMicrophoneStats, nLocalMicrophoneStatsSize);
			VidyoEndpointStatsFreelocalCameraStatsArrayNative(nLocalCameraStats, nLocalCameraStatsSize);
		}
	};
}
