// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LocalRendererStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoLocalRendererStats reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern MediaFormat VidyoLocalRendererStatsGetformatNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStatsGetframeIntervalMeasuredNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStatsGetframeIntervalSetNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStatsGetheightNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLocalRendererStatsGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLocalRendererStatsGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoLocalRendererStatsGettotalFramesNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoLocalRendererStatsGettotalPixelsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStatsGetwidthNative(IntPtr obj);

		public MediaFormat format;
		public ulong frameIntervalMeasured;
		public ulong frameIntervalSet;
		public ulong height;
		public String id;
		public String name;
		public uint totalFrames;
		public uint totalPixels;
		public ulong width;
		public LocalRendererStats(IntPtr obj){
			objPtr = obj;

			format = VidyoLocalRendererStatsGetformatNative(objPtr);
			frameIntervalMeasured = VidyoLocalRendererStatsGetframeIntervalMeasuredNative(objPtr);
			frameIntervalSet = VidyoLocalRendererStatsGetframeIntervalSetNative(objPtr);
			height = VidyoLocalRendererStatsGetheightNative(objPtr);
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLocalRendererStatsGetidNative(objPtr));
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLocalRendererStatsGetnameNative(objPtr));
			totalFrames = VidyoLocalRendererStatsGettotalFramesNative(objPtr);
			totalPixels = VidyoLocalRendererStatsGettotalPixelsNative(objPtr);
			width = VidyoLocalRendererStatsGetwidthNative(objPtr);
		}
	};
}
