// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LoggerCategory{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoLoggerCategory reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLoggerCategoryGetdescriptionNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLoggerCategoryGetlevelsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLoggerCategoryGetlevelsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLoggerCategoryFreelevelsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLoggerCategoryGetnameNative(IntPtr obj);

		public String description;
		public List<String> levels;
		public String name;
		public LoggerCategory(IntPtr obj){
			objPtr = obj;

			List<String> csLevels = new List<String>();
			int nLevelsSize = 0;
			IntPtr nLevels = VidyoLoggerCategoryGetlevelsArrayNative(VidyoLoggerCategoryGetlevelsNative(objPtr), ref nLevelsSize);
			int nLevelsIndex = 0;
			while (nLevelsIndex < nLevelsSize) {
				csLevels.Add((string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(Marshal.ReadIntPtr(nLevels + (nLevelsIndex * Marshal.SizeOf(nLevels)))));
				nLevelsIndex++;
			}

			description = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLoggerCategoryGetdescriptionNative(objPtr));
			levels = csLevels;
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLoggerCategoryGetnameNative(objPtr));
			VidyoLoggerCategoryFreelevelsArrayNative(nLevels, nLevelsSize);
		}
	};
}
