// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LogStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoLogStats reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogErrorDataStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogErrorDataStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLogStatsFreelogErrorDataStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogWarningDataStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogWarningDataStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLogStatsFreelogWarningDataStatsArrayNative(IntPtr obj, int size);

		public List<LogDataStats> logErrorDataStats;
		public List<LogDataStats> logWarningDataStats;
		public LogStats(IntPtr obj){
			objPtr = obj;

			List<LogDataStats> csLogErrorDataStats = new List<LogDataStats>();
			int nLogErrorDataStatsSize = 0;
			IntPtr nLogErrorDataStats = VidyoLogStatsGetlogErrorDataStatsArrayNative(VidyoLogStatsGetlogErrorDataStatsNative(objPtr), ref nLogErrorDataStatsSize);
			int nLogErrorDataStatsIndex = 0;
			while (nLogErrorDataStatsIndex < nLogErrorDataStatsSize) {
				LogDataStats csTlogErrorDataStats = new LogDataStats(Marshal.ReadIntPtr(nLogErrorDataStats + (nLogErrorDataStatsIndex * Marshal.SizeOf(nLogErrorDataStats))));
				csLogErrorDataStats.Add(csTlogErrorDataStats);
				nLogErrorDataStatsIndex++;
			}

			List<LogDataStats> csLogWarningDataStats = new List<LogDataStats>();
			int nLogWarningDataStatsSize = 0;
			IntPtr nLogWarningDataStats = VidyoLogStatsGetlogWarningDataStatsArrayNative(VidyoLogStatsGetlogWarningDataStatsNative(objPtr), ref nLogWarningDataStatsSize);
			int nLogWarningDataStatsIndex = 0;
			while (nLogWarningDataStatsIndex < nLogWarningDataStatsSize) {
				LogDataStats csTlogWarningDataStats = new LogDataStats(Marshal.ReadIntPtr(nLogWarningDataStats + (nLogWarningDataStatsIndex * Marshal.SizeOf(nLogWarningDataStats))));
				csLogWarningDataStats.Add(csTlogWarningDataStats);
				nLogWarningDataStatsIndex++;
			}

			logErrorDataStats = csLogErrorDataStats;
			logWarningDataStats = csLogWarningDataStats;
			VidyoLogStatsFreelogWarningDataStatsArrayNative(nLogWarningDataStats, nLogWarningDataStatsSize);
			VidyoLogStatsFreelogErrorDataStatsArrayNative(nLogErrorDataStats, nLogErrorDataStatsSize);
		}
	};
}
