// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public enum MediaFormat{
		MediaformatIN16,
		MediaformatFL32,
		MediaformatNULL,
		MediaformatI420,
		MediaformatYU12,
		MediaformatYUYV,
		MediaformatYUY2,
		Mediaformatyuvs,
		Mediaformat2vuy,
		MediaformatUYVY,
		MediaformatHDYC,
		Mediaformatyuv2,
		Mediaformatyuvu,
		MediaformatNV12,
		MediaformatNV21,
		Mediaformat24BG,
		Mediaformatraw,
		MediaformatBGRA,
		MediaformatRGBA,
		MediaformatARGB,
		MediaformatBYR1,
		MediaformatBYR2,
		MediaformatJPEG,
		MediaformatMJPG,
		Mediaformatdmb1,
		Mediaformatavc1,
		Mediaformathvc1,
		MediaformatM420,
		Mediaformat420f,
		Mediaformat420v,
		MediaformatY8
	}
}
