// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class RoomInfo{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoRoomInfo reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRoomInfoGetcreationTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetdescriptionNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetextensionNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoRoomInfoGetisFavoriteNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoRoomInfoGetisMembersOnlyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoRoomInfoGetisPasswordProtectedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoRoomInfoGetisPublicNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetlanguageNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRoomInfoGetmaxParticipantsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetmessageListNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetmessageListArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoFreemessageListArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern int VidyoRoomInfoGetnumUsersNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetownerListNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetownerListArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoFreeownerListArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern Room.RoomType VidyoRoomInfoGettypeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetuserListNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetuserListArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoFreeuserListArrayNative(IntPtr obj, int size);

		public ulong creationTime;
		public String description;
		public String extension;
		public String id;
		public Boolean isFavorite;
		public Boolean isMembersOnly;
		public Boolean isPasswordProtected;
		public Boolean isPublic;
		public String language;
		public uint maxParticipants;
		public List<ChatMessage> messageList;
		public String name;
		public int numUsers;
		public List<String> ownerList;
		public Room.RoomType type;
		public List<String> userList;
		public RoomInfo(IntPtr obj){
			objPtr = obj;

			List<ChatMessage> csMessageList = new List<ChatMessage>();
			int nMessageListSize = 0;
			IntPtr nMessageList = VidyoRoomInfoGetmessageListArrayNative(VidyoRoomInfoGetmessageListNative(objPtr), ref nMessageListSize);
			int nMessageListIndex = 0;
			while (nMessageListIndex < nMessageListSize) {
				ChatMessage csTmessageList = new ChatMessage(Marshal.ReadIntPtr(nMessageList + (nMessageListIndex * Marshal.SizeOf(nMessageList))));
				csMessageList.Add(csTmessageList);
				nMessageListIndex++;
			}

			List<String> csOwnerList = new List<String>();
			int nOwnerListSize = 0;
			IntPtr nOwnerList = VidyoRoomInfoGetownerListArrayNative(VidyoRoomInfoGetownerListNative(objPtr), ref nOwnerListSize);
			int nOwnerListIndex = 0;
			while (nOwnerListIndex < nOwnerListSize) {
				csOwnerList.Add((string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(Marshal.ReadIntPtr(nOwnerList + (nOwnerListIndex * Marshal.SizeOf(nOwnerList)))));
				nOwnerListIndex++;
			}

			List<String> csUserList = new List<String>();
			int nUserListSize = 0;
			IntPtr nUserList = VidyoRoomInfoGetuserListArrayNative(VidyoRoomInfoGetuserListNative(objPtr), ref nUserListSize);
			int nUserListIndex = 0;
			while (nUserListIndex < nUserListSize) {
				csUserList.Add((string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(Marshal.ReadIntPtr(nUserList + (nUserListIndex * Marshal.SizeOf(nUserList)))));
				nUserListIndex++;
			}

			creationTime = VidyoRoomInfoGetcreationTimeNative(objPtr);
			description = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetdescriptionNative(objPtr));
			extension = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetextensionNative(objPtr));
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetidNative(objPtr));
			isFavorite = VidyoRoomInfoGetisFavoriteNative(objPtr);
			isMembersOnly = VidyoRoomInfoGetisMembersOnlyNative(objPtr);
			isPasswordProtected = VidyoRoomInfoGetisPasswordProtectedNative(objPtr);
			isPublic = VidyoRoomInfoGetisPublicNative(objPtr);
			language = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetlanguageNative(objPtr));
			maxParticipants = VidyoRoomInfoGetmaxParticipantsNative(objPtr);
			messageList = csMessageList;
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetnameNative(objPtr));
			numUsers = VidyoRoomInfoGetnumUsersNative(objPtr);
			ownerList = csOwnerList;
			type = VidyoRoomInfoGettypeNative(objPtr);
			userList = csUserList;
			VidyoRoomInfoFreeuserListArrayNative(nUserList, nUserListSize);
			VidyoRoomInfoFreeownerListArrayNative(nOwnerList, nOwnerListSize);
			VidyoRoomInfoFreemessageListArrayNative(nMessageList, nMessageListSize);
		}
	};
}
