// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class VideoPlane{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoVideoPlane reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoVideoPlaneGetbufferNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoVideoPlaneGetheightNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoVideoPlaneGetoffsetNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoVideoPlaneGetpitchNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoVideoPlaneGetsizeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoVideoPlaneGetwidthNative(IntPtr obj);

		public IntPtr buffer;
		public ulong height;
		public ulong offset;
		public ulong pitch;
		public ulong size;
		public ulong width;
		public VideoPlane(IntPtr obj){
			objPtr = obj;

			buffer = VidyoVideoPlaneGetbufferNative(objPtr);
			height = VidyoVideoPlaneGetheightNative(objPtr);
			offset = VidyoVideoPlaneGetoffsetNative(objPtr);
			pitch = VidyoVideoPlaneGetpitchNative(objPtr);
			size = VidyoVideoPlaneGetsizeNative(objPtr);
			width = VidyoVideoPlaneGetwidthNative(objPtr);
		}
	};
}
