// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class ChatMessage{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoChatMessage reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoChatMessageGetbodyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern long VidyoChatMessageGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ChatMessageSenderType VidyoChatMessageGetsenderTypeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoChatMessageGettimestampNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ChatMessageType VidyoChatMessageGettypeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoChatMessageGetuserIdNative(IntPtr obj);

		public enum ChatMessageSenderType{
			ChatmessagesendertypeUser,
			ChatmessagesendertypeRoom,
			ChatmessagesendertypeSystem,
			ChatmessagesendertypeNone
		}
		public enum ChatMessageType{
			ChatmessagetypeChat,
			ChatmessagetypeMediaStart,
			ChatmessagetypeMediaStop
		}
		public enum ChatMessageTypingIndication{
			ChatmessagetypingindicationActive,
			ChatmessagetypingindicationComposing,
			ChatmessagetypingindicationGone,
			ChatmessagetypingindicationInactive,
			ChatmessagetypingindicationPaused,
			ChatmessagetypingindicationNone
		}
		public String body;
		public long id;
		public ChatMessageSenderType senderType;
		public ulong timestamp;
		public ChatMessageType type;
		public String userId;
		public ChatMessage(IntPtr obj){
			objPtr = obj;

			body = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoChatMessageGetbodyNative(objPtr));
			id = VidyoChatMessageGetidNative(objPtr);
			senderType = VidyoChatMessageGetsenderTypeNative(objPtr);
			timestamp = VidyoChatMessageGettimestampNative(objPtr);
			type = VidyoChatMessageGettypeNative(objPtr);
			userId = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoChatMessageGetuserIdNative(objPtr));
		}
	};
}
