// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LatencyTestDataStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoLatencyTestDataStats reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLatencyTestDataStatsGetaddressNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoLatencyTestDataStatsGetlatencyMsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoLatencyTestDataStatsGetlatitudeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoLatencyTestDataStatsGetlongitudeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLatencyTestDataStatsGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoLatencyTestDataStatsGetresponseReceivedNative(IntPtr obj);

		public String address;
		public uint latencyMs;
		public double latitude;
		public double longitude;
		public String name;
		public Boolean responseReceived;
		public LatencyTestDataStats(IntPtr obj){
			objPtr = obj;

			address = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLatencyTestDataStatsGetaddressNative(objPtr));
			latencyMs = VidyoLatencyTestDataStatsGetlatencyMsNative(objPtr);
			latitude = VidyoLatencyTestDataStatsGetlatitudeNative(objPtr);
			longitude = VidyoLatencyTestDataStatsGetlongitudeNative(objPtr);
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLatencyTestDataStatsGetnameNative(objPtr));
			responseReceived = VidyoLatencyTestDataStatsGetresponseReceivedNative(objPtr);
		}
	};
}
