// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class MeetingAttendee{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoMeetingAttendee reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingAttendeeGetemailNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingAttendeeGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern AttendeeParticipationRole VidyoMeetingAttendeeGetroleNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern AttendeeParticipationStatus VidyoMeetingAttendeeGetstatusNative(IntPtr obj);

		public enum AttendeeParticipationRole{
			AttendeeparticipationroleChair,
			AttendeeparticipationroleRequired,
			AttendeeparticipationroleOptional,
			AttendeeparticipationroleInformational
		}
		public enum AttendeeParticipationStatus{
			AttendeeparticipationstatusNeedsAction,
			AttendeeparticipationstatusOrganized,
			AttendeeparticipationstatusAccepted,
			AttendeeparticipationstatusDeclined,
			AttendeeparticipationstatusTentative,
			AttendeeparticipationstatusDelegated,
			AttendeeparticipationstatusNone,
			AttendeeparticipationstatusCompleted,
			AttendeeparticipationstatusInProcess
		}
		public String email;
		public String name;
		public AttendeeParticipationRole role;
		public AttendeeParticipationStatus status;
		public MeetingAttendee(IntPtr obj){
			objPtr = obj;

			email = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingAttendeeGetemailNative(objPtr));
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingAttendeeGetnameNative(objPtr));
			role = VidyoMeetingAttendeeGetroleNative(objPtr);
			status = VidyoMeetingAttendeeGetstatusNative(objPtr);
		}
	};
}
